// src/lib/server/backup.ts
// Runs backup.sh on the Minecraft VM via SSH using a pre-configured SSH key.
//
// The SSH key pair is generated by scripts/src/lib/setup/backup_ssh.ts and:
//   - Public key  → added to mc-backup user's authorized_keys on the VM
//   - Private key → stored as BACKUP_SSH_KEY (Netlify env / local .env)

import { Client } from 'ssh2';
import type { GetSignedUrlResponse } from '@google-cloud/storage';
import { VM_IP } from '$config';
import { env } from '$env/dynamic/private';
import { logger } from '$logger';
import { setServerStatus } from '$lib/server/firestore';
import { getApp } from '$lib/server/firebase';
import { getStorage } from 'firebase-admin/storage';

// BACKUP_SSH_KEY is stored base64-encoded in .env (PEM has newlines
// which break .env file parsing). Decode it before use.
const BACKUP_SSH_KEY = env.BACKUP_SSH_KEY
  ? Buffer.from(env.BACKUP_SSH_KEY, 'base64').toString('utf-8')
  : undefined;
const SSH_USER = 'mc-backup';
const SSH_PORT = 22;
const SCRIPT_PATH = '/mnt/disks/data/mc-backup.sh';

// ── SSH connection ──────────────────────────────────────────────────────────

function sshExec(
  host: string,
  username: string,
  privateKey: string,
  command: string,
): Promise<{ stdout: string; stderr: string }> {
  return new Promise((resolve, reject) => {
    const conn = new Client();
    const stdout: string[] = [];
    const stderr: string[] = [];

    conn.on('ready', () => {
      conn.exec(command, (err, stream) => {
        if (err) {
          conn.end();
          reject(err);
          return;
        }
        stream.on('close', (code: number) => {
          conn.end();
          if (code === 0) {
            resolve({ stdout: stdout.join(''), stderr: stderr.join('') });
          } else {
            reject(
              new Error(
                `backup.sh exited with code ${code}: ${stderr.join('') || stdout.join('').slice(0, 300)}`,
              ),
            );
          }
        });
        stream.on('data', (data: Buffer) => {
          stdout.push(data.toString());
        });
        stream.stderr.on('data', (data: Buffer) => {
          stderr.push(data.toString());
        });
      });
    });

    conn.on('error', reject);

    conn.connect({
      host,
      port: SSH_PORT,
      username,
      privateKey,
      readyTimeout: 15000,
    });
  });
}

// ── Signed upload URL ────────────────────────────────────────────────────────

async function generateUploadUrl(): Promise<string> {
  const app = getApp();
  const bucket = getStorage(app).bucket();
  const date = new Date();
  const path = `backup/${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}_${String(date.getHours()).padStart(2, '0')}:00.tar.gz`;

  const signedUrlResult = (await bucket.file(path).getSignedUrl({
    action: 'write',
    expires: Date.now() + 15 * 60 * 1000, // 15 minutes
    contentType: 'application/gzip',
  })) as unknown as GetSignedUrlResponse;
  const url = signedUrlResult[0];

  logger.info('backup', `signed URL generated for ${path}`);
  return url;
}

// ── Public API ──────────────────────────────────────────────────────────────

export async function runBackup(): Promise<void> {
  logger.info('backup', 'starting backup on VM');

  if (!BACKUP_SSH_KEY) {
    throw new Error('BACKUP_SSH_KEY env var not set — run project setup first');
  }

  try {
    // 1. Generate a signed upload URL (expires in 15 min)
    const uploadUrl = await generateUploadUrl();

    // 2. SSH into the VM and run backup.sh with the signed URL
    //    The script creates the tar and uploads it via curl
    const command = `sudo ${SCRIPT_PATH} '${uploadUrl}'`;
    const result = await sshExec(VM_IP, SSH_USER, BACKUP_SSH_KEY, command);

    logger.info('backup', 'backup completed on VM', {
      stdout: result.stdout.slice(0, 500),
    });
    await setServerStatus({ serverStatus: 'BACKUP_COMPLETE' });
  } catch (e) {
    const message = e instanceof Error ? e.message : String(e);
    logger.error('backup', `backup failed: ${message}`);
    await setServerStatus({ serverStatus: 'BACKUP_FAILED' });
    throw e;
  }
}
